%% Adaptive_He_3S_densemem_v3.m
% Adaptive stage for J.H. Table 5.5 He triplet, separated from raw/coarsening.
%
% Input:
%   JH_HeTriplet_coarsened_*_M*_nu*.mat generated by
%   JH_HeTriplet_part2_build_coarsen_debug_v1.m
%
% The adaptive stage uses exactly the same oneFuncs/twoBasis/params saved by
% the coarsening stage. It does not rebuild B_three^[0].

clear; clc; close all;
format long e;

coarseFiles = dir('JH_HeTriplet_coarsened_*_M*_nu*.mat');
if isempty(coarseFiles)
    error('Cannot find JH_HeTriplet_coarsened_*_M*_nu*.mat. Run JH_HeTriplet_part2_build_coarsen_debug_v1 first.');
end
[~,ord] = max([coarseFiles.datenum]);
coarseFile = coarseFiles(ord).name;
load(coarseFile, 'partT');

hfFile = partT.hfFile;
hf = partT.hf;
oneFuncs = partT.oneFuncs;
oneKeyMap = containers.Map('KeyType','char','ValueType','double');
for ii = 1:numel(oneFuncs), oneKeyMap(char(oneFuncs(ii).key)) = ii; end

Zcharge = partT.params.Zcharge;
Rnuc = partT.params.Rnuc;
sigma0 = partT.params.sigma0;
cscale = partT.params.cscale;
L0 = partT.params.L0;
D = partT.params.D;
ZsetMode = partT.params.ZsetMode;
centerConvention = partT.params.centerConvention;
centerForNeighbors = 'actual';
neighborMode = partT.params.neighborMode;
if isfield(partT.params,'detScaleMode'), detScaleMode = partT.params.detScaleMode; else, detScaleMode = 'l2_normalized'; end

updateMode = 'monotone_union';
importanceMode = 'partial_orthogonal';
E_ref_exact = partT.params.E_ref_exact;
E_ref_table = -2.17523;

kappa_max = 10;
max_inner = 5;
max_basis_allowed = 35000;
mass_tol = 1e-9;
verboseEig = false;

assemblyOpts = struct();
assemblyOpts.mode = 'cpu_parfor_sparse';
assemblyOpts.rowBlockSize = 256;
assemblyOpts.startPool = true;
assemblyOpts.dropTolS = 0;
assemblyOpts.dropTolH = 0;
assemblyOpts.showRowProgress = true;
assemblyOpts.upperTriangle = true;
assemblyOpts.detScaleMode = detScaleMode;

% Large-M assembly pruning. Conservative by default.
% This only affects sparse assembly/storage. Set enable=false for bitwise old logic.
assemblyDrop = struct();
assemblyDrop.enable = true;
assemblyDrop.Mmin = 15000;
assemblyDrop.dropTolS_large = 1e-14;
assemblyDrop.dropTolH_large = 1e-13;

% Dense-quality but lower-peak-memory eigensolver.
% Key change: do NOT form full(H).  Project H through sparse H*X in blocks.
solverOpts = struct();
solverOpts.projectBlockSize = 256;
solverOpts.autoCapKeptDim = false;     % true only if you must cap memory at the cost of variational space
solverOpts.maxKeptDim = 18000;         % used only when autoCapKeptDim=true
solverOpts.forceSymmetrizeInSolver = false; % matrices were already symmetrized after assembly

recordOpts = struct();
recordOpts.saveRecordsEveryInner = true;
recordOpts.saveBasisEveryMRecord = true;
recordOpts.saveEveryInnerPrefix = 'JH_HeTriplet_basis_byM_fromCoarse';
recordOpts.computeBlockEnergyEachInner = true;
recordOpts.blockEnergyMaxM = 12000;     % skip diagnostic block-energy for huge M
recordOpts.saveBasisOnMUpdate = true;   % save immediately whenever M grows
recordOpts.updateBasisPrefix = 'JH_HeTriplet_basis_after_M_update';

% Resume option: if true, load the latest basis saved immediately after an M update.
% This avoids rerunning earlier adaptive steps; the script will assemble/solve from that M.
resumeOpts = struct();
resumeOpts.enable = false;
resumeOpts.file = '';  % leave empty to use latest JH_HeTriplet_basis_after_M_update_*.mat

oneCache = reset_one_cache(Zcharge, Rnuc);
oneCache = update_one_cache(oneCache, oneFuncs, Zcharge, Rnuc);

fprintf('\n============================================================\n');
fprintf('J.H. He triplet Table 5.5 adaptive FROM COARSENED FILE\n');
fprintf('coarseFile: %s\n', coarseFile);
fprintf('M0=%d | E0=%.15f | detScale=%s | neighbor=%s | update=%s\n', ...
    numel(partT.twoBasis0), partT.E0, detScaleMode, neighborMode, updateMode);
fprintf('Target: kappa=1 M=141 E=-2.174698; kappa=5 M=147 E=-2.174698.\n');
fprintf('============================================================\n');

%% ============================================================
% Adaptive loop
% =============================================================
twoBasis = partT.twoBasis0;

if resumeOpts.enable
    if isempty(resumeOpts.file)
        fup = dir(sprintf('%s_*.mat', recordOpts.updateBasisPrefix));
        if isempty(fup)
            error('resumeOpts.enable=true but no %s_*.mat file was found.', recordOpts.updateBasisPrefix);
        end
        [~,iu] = max([fup.datenum]);
        resumeFile = fup(iu).name;
    else
        resumeFile = resumeOpts.file;
    end
    R = load(resumeFile);
    if isfield(R,'twoBasis_saved')
        twoBasis = R.twoBasis_saved;
    else
        error('Resume file %s does not contain twoBasis_saved.', resumeFile);
    end
    if isfield(R,'oneFuncs_saved')
        oneFuncs = R.oneFuncs_saved;
    else
        error('Resume file %s does not contain oneFuncs_saved.', resumeFile);
    end
    oneKeyMap = containers.Map('KeyType','char','ValueType','double');
    for ii = 1:numel(oneFuncs), oneKeyMap(char(oneFuncs(ii).key)) = ii; end
    fprintf('RESUME enabled: loaded %s | M=%d | oneFuncs=%d\n', resumeFile, numel(twoBasis), numel(oneFuncs));
end

[twoBasis, twoKeyMap] = unique_twobasis(twoBasis);
for i = 1:numel(twoBasis)
    twoKeyMap(char(twoBasis(i).key)) = i;
end

twoCache = []; 
records = repmat(empty_record(), kappa_max, 1);
recordsByM = repmat(empty_m_record(), 0, 1);
sampleID = 0;
tGlobal = tic;

for kappa = 1:kappa_max
    epsK = 2^(-kappa);
    fprintf('\n############################################################\n');
    fprintf('kappa = %d, epsilon = %.6e\n', kappa, epsK);
    fprintf('############################################################\n');

    for inner = 1:max_inner
        tInner = tic;
        M = numel(twoBasis);
        counts = count_blocks(twoBasis);
        fprintf('\n  inner %d | M=%d | Mone/two_uu = %d / %d\n', inner, M, counts.one_total, counts.two_uu);

        if M > max_basis_allowed
            error('M=%d exceeds max_basis_allowed=%d.', M, max_basis_allowed);
        end

        tAsm = tic;
        oneCache = update_one_cache(oneCache, oneFuncs, Zcharge, Rnuc);

        assemblyOptsNow = assemblyOpts;
        if assemblyDrop.enable && M >= assemblyDrop.Mmin
            assemblyOptsNow.dropTolS = max(assemblyOptsNow.dropTolS, assemblyDrop.dropTolS_large);
            assemblyOptsNow.dropTolH = max(assemblyOptsNow.dropTolH, assemblyDrop.dropTolH_large);
            fprintf('  large-M pruning enabled: dropTolS=%.1e, dropTolH=%.1e\n', ...
                assemblyOptsNow.dropTolS, assemblyOptsNow.dropTolH);
        end

        [S2,H2,asmInfo] = assemble_twobody_matrices(twoBasis, oneCache, oneFuncs, assemblyOptsNow);
        assemblyTime = toc(tAsm);
        fprintf('  assembly: %.2f s | nnz(S/H)=%.3e/%.3e | est sparse GB=%.3f\n', ...
            assemblyTime, nnz(S2), nnz(H2), estimate_sparse_pair_gb(S2,H2));

        % Free temporary assembly bookkeeping before the dense-quality solve.
        clear asmInfo;

        tSol = tic;
        [E0, coeff, nkeep, solverInfo] = solve_ground_projected(H2, S2, mass_tol, verboseEig, E_ref_exact, solverOpts);
        solveTime = toc(tSol);
        fprintf('  solve: %.2f s | E=%.15f | err=%.3e | kept=%d | residual=%.3e\n', ...
            solveTime, E0, abs(E0-E_ref_exact), nkeep, solverInfo.residual);

        tImp = tic;
        switch lower(importanceMode)
            case 'partial_orthogonal'
                scores = partial_orthogonal_importance(coeff, S2);
            case 'raw'
                scores = abs(coeff(:));
            otherwise
                error('Unknown importanceMode.');
        end
        important = scores >= epsK;
        if ~any(important)
            [~,imx] = max(scores); important(imx) = true;
        end
        importanceTime = toc(tImp);
        fprintf('  important=%d / %d | score max=%.3e, min(nonzero)=%.3e | importance %.2f s\n', ...
            nnz(important), M, max(scores), min(scores(scores>0)), importanceTime);

        if recordOpts.computeBlockEnergyEachInner && M <= recordOpts.blockEnergyMaxM
            tBE = tic;
            be = compute_block_energy_contributions(coeff, H2, twoBasis);
            blockEnergyTime = toc(tBE);
        else
            be = empty_block_energy(); blockEnergyTime = 0;
            if recordOpts.computeBlockEnergyEachInner && M > recordOpts.blockEnergyMaxM
                fprintf('  block-energy diagnostic skipped for M=%d > %d to reduce memory.\n', ...
                    M, recordOpts.blockEnergyMaxM);
            end
        end

        tGrow = tic;
        importantBasis = twoBasis(important);
        [growBasis, oneFuncs, oneKeyMap] = grow_important_det_basis(importantBasis, oneFuncs, oneKeyMap, ...
            sigma0, cscale, D, ZsetMode, centerConvention, centerForNeighbors, neighborMode);
        switch lower(updateMode)
            case 'monotone_union'
                candidate = [twoBasis, growBasis];
            case 'paper_reset'
                candidate = growBasis;
            otherwise
                error('Unknown updateMode: %s', updateMode);
        end
        [twoBasisNew, newMap] = unique_twobasis(candidate);
        added = numel(twoBasisNew) - numel(twoBasis);
        growTime = toc(tGrow);
        fprintf('  grown raw=%d | unique new M=%d | added=%d | grow %.2f s\n', ...
            numel(candidate), numel(twoBasisNew), added, growTime);

        updateBasisFile = '';
        if added > 0 && isfield(recordOpts,'saveBasisOnMUpdate') && recordOpts.saveBasisOnMUpdate
            tUpdSave = tic;
            oldM_for_update = numel(twoBasis);
            newBasis = twoBasisNew(oldM_for_update+1:end);
            updateBasisFile = sprintf('%s_k%d_inner%d_M%d_to_%d_added%d.mat', ...
                recordOpts.updateBasisPrefix, kappa, inner, oldM_for_update, numel(twoBasisNew), added);
            params = partT.params; 
            updateInfo = struct('kappa',kappa,'inner',inner,'oldM',oldM_for_update, ...
                'newM',numel(twoBasisNew),'added',added,'E_before_update',E0, ...
                'err_before_update',abs(E0-E_ref_exact),'coarseFile',coarseFile); 
            twoBasis_saved = twoBasisNew; 
            oneFuncs_saved = oneFuncs; 
            save(updateBasisFile, 'oneFuncs_saved', 'twoBasis_saved', 'newBasis', 'updateInfo', 'params', '-v7.3');
            fprintf('  saved updated basis: %s | save %.2fs\n', updateBasisFile, toc(tUpdSave));
        end

        sampleID = sampleID + 1;
        [recordsByM, tSave, basisFile] = append_M_record_and_checkpoint(recordsByM, sampleID, ...
            kappa, inner, epsK, twoBasis, E0, abs(E0-E_ref_exact), coeff, scores, important, ...
            growBasis, added, counts, be, solverInfo, assemblyTime, solveTime, importanceTime, ...
            blockEnergyTime, growTime, toc(tInner), toc(tGlobal), oneFuncs, partT.params, recordOpts);

        fprintf('  M-record #%d | kappa.inner=%d.%d | M=%d | err=%.3e | tAsm=%.1fs tSol=%.1fs tGrow=%.1fs tSave=%.1fs | cum=%.1fs\n', ...
            sampleID, kappa, inner, M, abs(E0-E_ref_exact), assemblyTime, solveTime, growTime, tSave, toc(tGlobal));

        if added <= 0
            fprintf('  inner closure reached for kappa=%d; keep M=%d.\n', kappa, M);
            break;
        end

        % Important: clear large matrices before carrying the enlarged basis into the next inner loop.
        clear S2 H2 scores important coeff Horth X;
        twoBasis = twoBasisNew;
        twoKeyMap = newMap; 
    end

    records(kappa) = make_record(kappa, numel(twoBasis), E0, abs(E0-E_ref_exact), count_blocks(twoBasis), be, inner, solverInfo);
    fprintf('\n>>> record kappa=%d | M=%d | E=%.15f | err=%.3e | Mone=%d | Mtwo_uu=%d | inner=%d\n', ...
        kappa, records(kappa).M, records(kappa).E, records(kappa).err, records(kappa).Mone, records(kappa).Mtwo_uu, inner);
    fprintf('    row energy: Ezero=%.6f | Eone=%.6f | Etwo_uu=%.6f | sum=%.15f\n', ...
        records(kappa).Ezero, records(kappa).Eone, records(kappa).Etwo_uu, ...
        records(kappa).Ezero + records(kappa).Eone + records(kappa).Etwo_uu);
end

%% ============================================================
% 4. Summary and save
% =============================================================
fprintf('\n==================== TABLE 5.5 STYLE SUMMARY ====================\n');
fprintf(' kappa      M        E                    err          Mone      Mtwo_uu     Ezero      Eone       Etwo_uu\n');
for k = 1:kappa_max
    if records(k).M == 0, continue; end
    fprintf('%5d %8d  %.15f  %.3e  %8d %9d   %8.2f  %8.2f  %9.2e\n', ...
        records(k).kappa, records(k).M, records(k).E, records(k).err, ...
        records(k).Mone, records(k).Mtwo_uu, records(k).Ezero, records(k).Eone, records(k).Etwo_uu);
end

fprintf('\n==================== M-INDEXED INNER RECORDS ====================\n');
fprintf(' sample  k.i       M        E                    err        tAsm     tSol    tGrow   tInner  tCum\n');
for i = 1:numel(recordsByM)
    r = recordsByM(i);
    fprintf('%6d  %2d.%02d %8d  %.15f  %.3e  %8.1f %8.1f %8.1f %8.1f %8.1f\n', ...
        r.sampleID, r.kappa, r.inner, r.M, r.E, r.err, r.assemblyTime, r.solveTime, r.growTime, r.totalInnerTimeWithSave, r.cumulativeTime);
end

recordsByM_unique = unique_records_by_M_keep_best(recordsByM);
Tcsv = struct2table(recordsByM);
csvName = 'JH_HeTriplet_Table55_densemem_v3_M_records.csv';
writetable(Tcsv, csvName);
fprintf('\nSaved M-record CSV: %s\n', csvName);

finalState = struct();
finalState.hfFile = hfFile;
finalState.coarseFile = coarseFile;
finalState.params = partT.params;
finalState.records = records;
finalState.recordsByM = recordsByM;
finalState.recordsByM_unique = recordsByM_unique;
finalState.oneFuncs = oneFuncs;
finalState.twoBasis = twoBasis;
finalState.E_ref_exact = E_ref_exact;
finalFile = sprintf('JH_HeTriplet_densemem_v3_adaptive_basis_final_kappa%d_M%d.mat', kappa_max, numel(twoBasis));
save(finalFile, 'finalState', '-v7.3');
fprintf('Saved final adaptive basis/config only: %s\n', finalFile);

%% ========================================================================
% Local functions: records
% ========================================================================
function r = empty_record()
    r = struct('kappa',0,'M',0,'E',NaN,'err',NaN,'Mzero',0,'Mone',0,'Mtwo_uu',0, ...
        'Ezero',NaN,'Eone',NaN,'Etwo_uu',NaN,'inner',0,'solverResidual',NaN);
end

function r = make_record(kappa, M, E, err, counts, be, inner, solverInfo)
    r = empty_record();
    r.kappa = kappa; r.M = M; r.E = E; r.err = err;
    r.Mzero = counts.zero; r.Mone = counts.one_total; r.Mtwo_uu = counts.two_uu;
    r.Ezero = be.row.zero; r.Eone = be.row.one; r.Etwo_uu = be.row.two_uu;
    r.inner = inner; r.solverResidual = solverInfo.residual;
end

function r = empty_m_record()
    r = struct('sampleID',0,'kappa',0,'inner',0,'epsilon',NaN,'M',0, ...
        'Mzero',0,'Mone',0,'Mtwo_uu',0,'E',NaN,'err',NaN, ...
        'Ezero',NaN,'Eone',NaN,'Etwo_uu',NaN,'kept',0,'solverResidual',NaN, ...
        'assemblyTime',NaN,'solveTime',NaN,'importanceTime',NaN,'blockEnergyTime',NaN, ...
        'growTime',NaN,'saveTime',NaN,'totalInnerTimeNoSave',NaN,'totalInnerTimeWithSave',NaN, ...
        'cumulativeTime',NaN,'nImportant',0,'scoreMax',NaN,'scoreMinNonzero',NaN, ...
        'nGrowRaw',0,'nAdded',0,'basisFile','');
end

function [recordsByM, tSave, basisFile] = append_M_record_and_checkpoint(recordsByM, sampleID, ...
    kappa, inner, epsK, twoBasis, E, err, ~, scores, important, growBasis, added, counts, be, solverInfo, ...
    assemblyTime, solveTime, importanceTime, blockEnergyTime, growTime, innerTimeNoSave, cumTime, oneFuncs, params, recordOpts)
    t0 = tic;
    r = empty_m_record();
    r.sampleID = sampleID; r.kappa = kappa; r.inner = inner; r.epsilon = epsK;
    r.M = numel(twoBasis); r.Mzero = counts.zero; r.Mone = counts.one_total; r.Mtwo_uu = counts.two_uu;
    r.E = E; r.err = err; r.Ezero = be.row.zero; r.Eone = be.row.one; r.Etwo_uu = be.row.two_uu;
    r.kept = solverInfo.kept; r.solverResidual = solverInfo.residual;
    r.assemblyTime = assemblyTime; r.solveTime = solveTime; r.importanceTime = importanceTime;
    r.blockEnergyTime = blockEnergyTime; r.growTime = growTime;
    r.totalInnerTimeNoSave = innerTimeNoSave; r.cumulativeTime = cumTime;
    r.nImportant = nnz(important); r.scoreMax = max(scores);
    sp = scores(scores>0); if isempty(sp), r.scoreMinNonzero = 0; else, r.scoreMinNonzero = min(sp); end
    r.nGrowRaw = numel(growBasis); r.nAdded = added;
    basisFile = '';
    if recordOpts.saveBasisEveryMRecord
        basisFile = sprintf('%s_sample%04d_kappa%d_inner%d_M%d.mat', recordOpts.saveEveryInnerPrefix, sampleID, kappa, inner, r.M);
        record = r; 
        save(basisFile, 'oneFuncs', 'twoBasis', 'record', 'params', '-v7.3');
    end
    r.basisFile = basisFile;
    tSave = toc(t0);
    r.saveTime = tSave;
    r.totalInnerTimeWithSave = innerTimeNoSave + tSave;
    recordsByM(end+1) = r; 
    if recordOpts.saveRecordsEveryInner
        save('JH_HeTriplet_records_live.mat', 'recordsByM', '-v7.3');
    end
end

function recordsUnique = unique_records_by_M_keep_best(recordsByM)
    if isempty(recordsByM), recordsUnique = recordsByM; return; end
    Mvals = [recordsByM.M].'; [Mu,~,ic] = unique(Mvals,'stable');
    recordsUnique = repmat(empty_m_record(), numel(Mu), 1);
    for i = 1:numel(Mu)
        idx = find(ic==i); [~,j] = min([recordsByM(idx).err]); recordsUnique(i) = recordsByM(idx(j));
    end
end

%% ========================================================================
% Local functions: basis and growth
% ========================================================================
function f = empty_onefunc()
    f = struct('kind','','type','','level',0,'j',[0 0 0],'z',[0 0 0],'terms',struct('coef',{},'alpha',{},'center',{}),'key',"");
end

function b = empty_twobasis()
    b = struct('block','','left',0,'right',0,'pReplaced',0,'key',"");
end

function [oneFuncs, oneKeyMap, id] = register_onefunc(oneFuncs, oneKeyMap, f)
    key = char(f.key);
    if isKey(oneKeyMap,key)
        id = oneKeyMap(key);
    else
        id = numel(oneFuncs)+1;
        oneFuncs(id) = f;
        oneKeyMap(key) = id;
    end
end

function [B, map] = append_basis(B, map, b)
    if isempty(b) || b.left == b.right, return; end
    key = char(b.key);
    if ~isKey(map,key)
        B(end+1) = b; 
        map(key) = numel(B);
    end
end

function b = make_det_basis(block, idA, idB, pReplaced)
    b = empty_twobasis();
    if idA == idB
        b.left = idA; b.right = idB; b.key = "ZERO_DET"; return;
    end
    ids = sort([idA idB]);
    b.block = char(block);
    b.left = ids(1);
    b.right = ids(2);
    b.pReplaced = pReplaced;
    b.key = string(sprintf('%s_D%d_%d_p%d', char(block), b.left, b.right, pReplaced));
end

function [Buniq, map] = unique_twobasis(B)
    if isempty(B), Buniq = B; map = containers.Map('KeyType','char','ValueType','double'); return; end
    keys = strings(numel(B),1);
    for i = 1:numel(B), keys(i)=string(B(i).key); end
    [~,ia] = unique(keys,'stable'); Buniq = B(ia);
    map = containers.Map('KeyType','char','ValueType','double');
    for i = 1:numel(Buniq), map(char(Buniq(i).key)) = i; end
end

function counts = count_blocks(twoBasis)
    M = numel(twoBasis);
    blocks = strings(M,1);
    for i = 1:M, blocks(i)=string(twoBasis(i).block); end
    counts = struct();
    counts.zero = nnz(blocks=="zero");
    counts.one_total = nnz(blocks=="one");
    counts.two_uu = nnz(blocks=="two_uu");
    counts.total = M;
end

function [growBasis, oneFuncs, oneKeyMap] = grow_important_det_basis(importantBasis, oneFuncs, oneKeyMap, ...
    sigma0, cscale, D, ZsetMode, centerConvention, centerForNeighbors, neighborMode)
    out = {}; k = 0;
    ref1 = 1; ref2 = 2;
    for ib = 1:numel(importantBasis)
        B = importantBasis(ib);
        switch string(B.block)
            case "zero"
                k = k+1; out{k} = B; %#ok<AGROW>
            case "one"
                if B.pReplaced == 1
                    active = setdiff([B.left B.right], ref2);
                    if isempty(active), continue; end
                    active = active(1); other = ref2;
                elseif B.pReplaced == 2
                    active = setdiff([B.left B.right], ref1);
                    if isempty(active), continue; end
                    active = active(1); other = ref1;
                else
                    % Fallback: grow whichever entry is not a reference.
                    ids = [B.left B.right]; active = ids(ids>2); if isempty(active), continue; end
                    active = active(1); other = ids(ids<=2); if isempty(other), other = ref1; else, other=other(1); end
                end
                neigh = onefunc_neighbors_both(oneFuncs(active), sigma0, cscale, D, ZsetMode, centerConvention, centerForNeighbors, neighborMode);
                for n = 1:numel(neigh)
                    [oneFuncs, oneKeyMap, nid] = register_onefunc(oneFuncs, oneKeyMap, neigh(n));
                    k = k+1; out{k} = make_det_basis('one', nid, other, B.pReplaced); %#ok<AGROW>
                end
            case "two_uu"
                fL = oneFuncs(B.left); fR = oneFuncs(B.right);
                neighL = onefunc_neighbors_both(fL, sigma0, cscale, D, ZsetMode, centerConvention, centerForNeighbors, neighborMode);
                neighR = onefunc_neighbors_both(fR, sigma0, cscale, D, ZsetMode, centerConvention, centerForNeighbors, neighborMode);
                for n = 1:numel(neighL)
                    [oneFuncs, oneKeyMap, nid] = register_onefunc(oneFuncs, oneKeyMap, neighL(n));
                    if nid ~= B.right
                        k = k+1; out{k} = make_det_basis('two_uu', nid, B.right, 0); %#ok<AGROW>
                    end
                end
                for n = 1:numel(neighR)
                    [oneFuncs, oneKeyMap, nid] = register_onefunc(oneFuncs, oneKeyMap, neighR(n));
                    if nid ~= B.left
                        k = k+1; out{k} = make_det_basis('two_uu', B.left, nid, 0); %#ok<AGROW>
                    end
                end
        end
    end
    if isempty(out), growBasis = importantBasis([]); else, growBasis = [out{:}]; end
end

%% ========================================================================
% Local functions: frame and neighbors
% ========================================================================
function frame = make_initial_frame(sigma0, cscale, L, D, ZsetMode, centerConvention)
    % Same finite b^{(L)}_{sigma,c} convention as the verified singlet He code:
    %   27 coarse phi functions plus 26 second-order wavelet functions per level.
    % Hence signed Zset gives 27 + 26*(L-1), e.g. 183 for L=7.
    cellF = {}; k = 0;
    vals = -1:1;
    [J1,J2,J3] = ndgrid(vals,vals,vals);
    JJ = [J1(:),J2(:),J3(:)];
    for i = 1:size(JJ,1)
        k=k+1; cellF{k}=make_phi(sigma0,cscale,0,JJ(i,:),D); %#ok<AGROW>
    end
    if L >= 2
        Zset = generate_z_set(D,ZsetMode);
        for l = 0:(L-2)
            for iz = 1:size(Zset,1)
                z = Zset(iz,:);
                j = -z;
                k=k+1; cellF{k}=make_psi(sigma0,cscale,l,j,z,D,centerConvention); %#ok<AGROW>
            end
        end
    end
    frame = unique_onefuncs([cellF{:}]);
end

function neigh = onefunc_neighbors_both(f, sigma0, cscale, D, ZsetMode, centerConvention, centerForNeighbors, neighborMode)
    if ~isfield(f,'kind') || string(f.kind) ~= "frame"
        neigh = f([]); return;
    end
    neigh = unique_onefuncs([neighbors_Ng_onefunc(f,sigma0,cscale,D,ZsetMode,centerConvention,centerForNeighbors,neighborMode), ...
                             neighbors_Ngplus_onefunc(f,sigma0,cscale,D,ZsetMode,centerConvention,centerForNeighbors,neighborMode)]);
end

function neigh = neighbors_Ng_onefunc(f, sigma0, cscale, D, ZsetMode, centerConvention, centerForNeighbors, neighborMode)
    Z0 = generate_neighbor_set(neighborMode);
    C0 = center_of_basis(f,cscale,centerForNeighbors);
    cellF = {}; k = 0;
    switch string(f.type)
        case "phi"
            step = 1/cscale;
            for n = 1:size(Z0,1)
                fs = functions_at_center(C0+step*Z0(n,:), sigma0, cscale, D, ZsetMode, centerConvention, centerForNeighbors, 'phi', 0);
                for j = 1:numel(fs), k=k+1; cellF{k}=fs(j); end %#ok<AGROW>
            end
        case "psi"
            l = f.level; step = 1/(cscale*2^(l+1));
            for n = 1:size(Z0,1)
                fs = functions_at_center(C0+step*Z0(n,:), sigma0, cscale, D, ZsetMode, centerConvention, centerForNeighbors, 'psi', l);
                for j = 1:numel(fs), k=k+1; cellF{k}=fs(j); end %#ok<AGROW>
            end
    end
    if isempty(cellF), neigh = f([]); else, neigh = unique_onefuncs([cellF{:}]); end
end

function neigh = neighbors_Ngplus_onefunc(f, sigma0, cscale, D, ZsetMode, centerConvention, centerForNeighbors, neighborMode)
    Z0 = generate_neighbor_set(neighborMode);
    C0 = center_of_basis(f,cscale,centerForNeighbors);
    cellF = {}; k = 0;
    switch string(f.type)
        case "phi"
            step = 1/(cscale*2); level = 0;
            for n = 1:size(Z0,1)
                fs = functions_at_center(C0+step*Z0(n,:), sigma0, cscale, D, ZsetMode, centerConvention, centerForNeighbors, 'psi', level);
                for j = 1:numel(fs), k=k+1; cellF{k}=fs(j); end %#ok<AGROW>
            end
        case "psi"
            level = f.level + 1; step = 1/(cscale*2^(f.level+2));
            for n = 1:size(Z0,1)
                fs = functions_at_center(C0+step*Z0(n,:), sigma0, cscale, D, ZsetMode, centerConvention, centerForNeighbors, 'psi', level);
                for j = 1:numel(fs), k=k+1; cellF{k}=fs(j); end %#ok<AGROW>
            end
    end
    if isempty(cellF), neigh = f([]); else, neigh = unique_onefuncs([cellF{:}]); end
end

function fs = functions_at_center(target, sigma0, cscale, D, ZsetMode, centerConvention, centerForNeighbors, kind, level)
    fsCell = {}; k = 0;
    switch string(kind)
        case "phi"
            scale = cscale * 2^level;
            j = round(target * scale);
            f = make_phi(sigma0,cscale,level,j,D);
            if norm(center_of_basis(f,cscale,centerForNeighbors)-target) < 1e-10
                k=k+1; fsCell{k}=f;
            end
        case "psi"
            Zset = generate_z_set(D,ZsetMode);
            scale = cscale * 2^level;
            for iz = 1:size(Zset,1)
                z = Zset(iz,:);
                switch lower(centerConvention)
                    case 'eq428'
                        j = round(target*scale - 0.5*z);
                    case 'cmap'
                        j = round(target*scale + 0.5*z);
                    otherwise
                        error('Unknown centerConvention.');
                end
                f = make_psi(sigma0,cscale,level,j,z,D,centerConvention);
                if norm(center_of_basis(f,cscale,centerForNeighbors)-target) < 1e-10
                    k=k+1; fsCell{k}=f; %#ok<AGROW>
                end
            end
    end
    if isempty(fsCell), fs = empty_onefunc(); fs = fs([]); else, fs = unique_onefuncs([fsCell{:}]); end
end

function Z0 = generate_neighbor_set(mode)
    switch lower(mode)
        case 'cross'
            Z0 = [0 0 0; 1 0 0; -1 0 0; 0 1 0; 0 -1 0; 0 0 1; 0 0 -1];
        case 'full'
            vals = -1:1; [A,B,C] = ndgrid(vals,vals,vals); Z0=[A(:),B(:),C(:)];
        otherwise
            error('Unknown neighborMode.');
    end
end

function Zset = generate_z_set(D, mode)
    switch lower(mode)
        case 'signed'
            vals = -1:1; [A,B,C] = ndgrid(vals,vals,vals); Zset=[A(:),B(:),C(:)]; Zset=Zset(any(Zset~=0,2),:);
        case 'binary'
            Zset = dec2bin(0:(2^D-1))-'0'; Zset=Zset(any(Zset~=0,2),:);
        otherwise
            error('Unknown ZsetMode.');
    end
end

function f = make_phi(sigma0,cscale,l,j,D)
    scale = cscale*2^l; width = sigma0/scale; alpha = 1/width^2; center = j/scale;
    term = struct('coef',1.0,'alpha',alpha,'center',center);
    f = empty_onefunc();
    f.kind='frame'; f.type='phi'; f.level=l; f.j=round(j); f.z=zeros(1,D); f.terms=term;
    f.key = canonical_key_from_center('phi',l,center,cscale);
end

function f = make_psi(sigma0,cscale,l,j,z,D,centerConvention)
    gamma = 2^(-D/2); Cpsi = (1 - (16/25)*gamma*sqrt(5) + gamma^2)^(-1/2);
    scale = cscale*2^l;
    switch lower(centerConvention)
        case 'eq428', center = (j + 0.5*z)/scale;
        case 'cmap',  center = (j - 0.5*z)/scale;
        otherwise, error('Unknown centerConvention.');
    end
    width1 = (sigma0/2)/scale; width2 = sigma0/scale;
    term1 = struct('coef',Cpsi,'alpha',1/width1^2,'center',center);
    term2 = struct('coef',-Cpsi*gamma,'alpha',1/width2^2,'center',center);
    f = empty_onefunc();
    f.kind='frame'; f.type='psi'; f.level=l; f.j=round(j); f.z=round(z); f.terms=[term1,term2];
    f.key = canonical_key_from_center('psi',l,center,cscale);
end

function key = canonical_key_from_center(type, level, center, cscale)
    scale = cscale*2^level; idx2 = round(2*scale*center);
    key = string(sprintf('%s_l%d_C2_%d_%d_%d', type, level, idx2(1), idx2(2), idx2(3)));
end

function C = center_of_basis(f,cscale,mode)
    switch lower(mode)
        case 'actual'
            C = f.terms(1).center;
        case 'paper_minus'
            if string(f.type)=="phi", C=f.j/cscale; else, C=(f.j-0.5*f.z)/(cscale*2^f.level); end
        otherwise
            error('Unknown center mode.');
    end
end

function B = unique_onefuncs(B)
    if isempty(B), return; end
    keys = strings(numel(B),1); for i=1:numel(B), keys(i)=string(B(i).key); end
    [~,ia] = unique(keys,'stable'); B = B(ia);
end

%% ========================================================================
% Local functions: assembly
% ========================================================================
function oneCache = reset_one_cache(Zcharge,Rnuc)
    oneCache = struct('S1',[],'H1',[],'M',0,'Zcharge',Zcharge,'Rnuc',Rnuc);
end

function oneCache = update_one_cache(oneCache, oneFuncs, Zcharge, Rnuc)
    Mnew = numel(oneFuncs); Mold = oneCache.M;
    if Mold == Mnew, return; end
    S1 = zeros(Mnew,Mnew); H1 = zeros(Mnew,Mnew);
    if Mold > 0
        S1(1:Mold,1:Mold) = oneCache.S1;
        H1(1:Mold,1:Mold) = oneCache.H1;
    end
    for i = 1:Mnew
        jStart = max(i, Mold+1);
        for j = jStart:Mnew
            [S,T,Ven] = contracted_one_particle(oneFuncs(i),oneFuncs(j),Zcharge,Rnuc);
            S1(i,j)=S; S1(j,i)=S;
            H1(i,j)=T+Ven; H1(j,i)=H1(i,j);
        end
    end
    oneCache.S1=S1; oneCache.H1=H1; oneCache.M=Mnew; oneCache.Zcharge=Zcharge; oneCache.Rnuc=Rnuc;
end

function [S2,H2,info] = assemble_twobody_matrices(twoBasis, oneCache, oneFuncs, opts)
    M = numel(twoBasis);
    S1 = oneCache.S1; H1 = oneCache.H1;
    td = build_term_data(oneFuncs);
    normInv = determinant_norm_inv(twoBasis,S1,opts);

    if strcmpi(opts.mode,'cpu_parfor_sparse') && opts.startPool
        try
            p = gcp('nocreate'); if isempty(p), parpool; end
        catch ME
            warning('Could not start parpool. Falling back to serial_sparse: %s', ME.message);
            opts.mode = 'serial_sparse';
        end
    end

    rowBlockSize = opts.rowBlockSize;
    S2 = sparse(M,M); H2 = sparse(M,M);
    t0 = tic;
    for r0 = 1:rowBlockSize:M
        r1 = min(M, r0+rowBlockSize-1);
        rows = r0:r1;
        [Srows,Hrows] = assemble_det_sparse_rows(twoBasis, rows, S1, H1, td, normInv, opts);
        S2(rows,:) = Srows;
        H2(rows,:) = Hrows;
        if opts.showRowProgress
            fprintf('    det sparse rows %d-%d / %d inserted, nnz(S/H)=%.3e/%.3e, elapsed %.1fs\n', ...
                r0,r1,M,nnz(S2),nnz(H2),toc(t0));
        end
    end
    if isfield(opts,'upperTriangle') && opts.upperTriangle
        S2 = triu(S2); H2 = triu(H2);
        S2 = S2 + triu(S2,1)';
        H2 = H2 + triu(H2,1)';
    else
        S2 = (S2+S2')/2; H2=(H2+H2')/2;
    end
    info = struct('M',M,'nnzS',nnz(S2),'nnzH',nnz(H2),'elapsed',toc(t0));
end

function normInv = determinant_norm_inv(tb,S1,opts)
    M = numel(tb);
    mode = 'l2_normalized';
    if isfield(opts,'detScaleMode'), mode = lower(char(string(opts.detScaleMode))); end
    switch mode
        case {'antisymmetrizer','unnormalized','raw_a'}
            normInv = ones(1,M);
        case {'l2_normalized','normalized_det','normalized'}
            normInv = zeros(1,M);
            for i = 1:M
                a=tb(i).left; b=tb(i).right;
                n2 = S1(a,a)*S1(b,b) - S1(a,b)*S1(b,a);
                if n2 < 1e-14, n2 = 1e-14; end
                normInv(i) = 1/sqrt(n2);
            end
        otherwise
            error('Unknown detScaleMode: %s', mode);
    end
end

function [Srows,Hrows] = assemble_det_sparse_rows(tb, rowIdx, S1, H1, td, normInv, opts)
    nr = numel(rowIdx); M = numel(tb);
    leftCols = [tb.left]; rightCols = [tb.right]; ncol = 1:M;
    switch lower(opts.mode)
        case 'cpu_parfor_sparse'
            IScell=cell(nr,1); JScell=cell(nr,1); VScell=cell(nr,1);
            IHcell=cell(nr,1); JHcell=cell(nr,1); VHcell=cell(nr,1);
            parfor ir = 1:nr
                [js,vs,jh,vh] = assemble_one_det_row(tb,rowIdx(ir),leftCols,rightCols,S1,H1,td,normInv,opts);
                IScell{ir}=ir*ones(numel(js),1); JScell{ir}=js(:); VScell{ir}=vs(:);
                IHcell{ir}=ir*ones(numel(jh),1); JHcell{ir}=jh(:); VHcell{ir}=vh(:);
            end
            IS=vertcat(IScell{:}); JS=vertcat(JScell{:}); VS=vertcat(VScell{:});
            IH=vertcat(IHcell{:}); JH=vertcat(JHcell{:}); VH=vertcat(VHcell{:});
        otherwise
            IS=[];JS=[];VS=[];IH=[];JH=[];VH=[];
            for ir = 1:nr
                [js,vs,jh,vh] = assemble_one_det_row(tb,rowIdx(ir),leftCols,rightCols,S1,H1,td,normInv,opts);
                IS=[IS; ir*ones(numel(js),1)]; JS=[JS; js(:)]; VS=[VS; vs(:)]; %#ok<AGROW>
                IH=[IH; ir*ones(numel(jh),1)]; JH=[JH; jh(:)]; VH=[VH; vh(:)]; %#ok<AGROW>
            end
    end
    Srows = sparse(IS,JS,VS,nr,M);
    Hrows = sparse(IH,JH,VH,nr,M);
end

function [js,vs,jh,vh] = assemble_one_det_row(tb,a,leftCols,rightCols,S1,H1,td,normInv,opts)
    i = tb(a).left; j = tb(a).right;
    k = leftCols; l = rightCols;
    if isfield(opts,'upperTriangle') && opts.upperTriangle
        upperMask = (1:numel(leftCols)) >= a;
    else
        upperMask = true(size(leftCols));
    end
    Sik = S1(i,k); Sjl = S1(j,l); Sil = S1(i,l); Sjk = S1(j,k);
    Hik = H1(i,k); Hjl = H1(j,l); Hil = H1(i,l); Hjk = H1(j,k);

    Sraw = Sik.*Sjl - Sil.*Sjk;
    Hone = Hik.*Sjl + Sik.*Hjl - Hil.*Sjk - Sil.*Hjk;
    Jdir = eri_row_vectorized_cpu(td, i, k, j, l);
    Jex  = eri_row_vectorized_cpu(td, i, l, j, k);
    Hraw = Hone + Jdir - Jex;
    fac = normInv(a) .* normInv;
    srow = Sraw .* fac;
    hrow = Hraw .* fac;
    maskS = upperMask & (abs(srow) >= opts.dropTolS);
    maskH = upperMask & (abs(hrow) >= opts.dropTolH);
    js = find(maskS); vs = srow(maskS);
    jh = find(maskH); vh = hrow(maskH);
end

function td = build_term_data(oneFuncs)
    M = numel(oneFuncs); maxT = 0;
    for i=1:M, maxT=max(maxT,numel(oneFuncs(i).terms)); end
    coef=zeros(M,maxT); alpha=zeros(M,maxT); cx=zeros(M,maxT); cy=zeros(M,maxT); cz=zeros(M,maxT);
    for i=1:M
        for t=1:numel(oneFuncs(i).terms)
            term=oneFuncs(i).terms(t);
            coef(i,t)=term.coef; alpha(i,t)=term.alpha; cx(i,t)=term.center(1); cy(i,t)=term.center(2); cz(i,t)=term.center(3);
        end
    end
    td=struct('coef',coef,'alpha',alpha,'cx',cx,'cy',cy,'cz',cz,'maxTerms',maxT);
end

function vrow = eri_row_vectorized_cpu(td, ia, ibVec, ic, idVec)
    nc = numel(ibVec); vrow = zeros(1,nc); T=td.maxTerms;
    for ta=1:T
        ca=td.coef(ia,ta); if ca==0, continue; end
        aA=td.alpha(ia,ta); Ax=td.cx(ia,ta); Ay=td.cy(ia,ta); Az=td.cz(ia,ta);
        for tc=1:T
            cc=td.coef(ic,tc); if cc==0, continue; end
            aC=td.alpha(ic,tc); Cx=td.cx(ic,tc); Cy=td.cy(ic,tc); Cz=td.cz(ic,tc);
            coefAC=ca*cc;
            for tb=1:T
                cb=td.coef(ibVec,tb).'; activeB=cb~=0; if ~any(activeB), continue; end
                aB_all=td.alpha(ibVec,tb).'; Bx_all=td.cx(ibVec,tb).'; By_all=td.cy(ibVec,tb).'; Bz_all=td.cz(ibVec,tb).';
                for td2=1:T
                    cd=td.coef(idVec,td2).'; mask=activeB & (cd~=0); if ~any(mask), continue; end
                    aB=aB_all(mask); Bx=Bx_all(mask); By=By_all(mask); Bz=Bz_all(mask);
                    idm=idVec(mask);
                    aD=td.alpha(idm,td2).'; Dx=td.cx(idm,td2).'; Dy=td.cy(idm,td2).'; Dz=td.cz(idm,td2).';
                    val=eri_primitive_vec(aA,Ax,Ay,Az,aB,Bx,By,Bz,aC,Cx,Cy,Cz,aD,Dx,Dy,Dz);
                    vrow(mask)=vrow(mask)+coefAC.*cb(mask).*cd(mask).*val;
                end
            end
        end
    end
end

function [S,T,Ven] = contracted_one_particle(f,g,Z,Rnuc)
    S=0;T=0;Ven=0;
    for a=1:numel(f.terms)
        A=f.terms(a);
        for b=1:numel(g.terms)
            B=g.terms(b);
            [s,t,v]=one_particle_primitive(A.alpha,A.center,B.alpha,B.center,Z,Rnuc);
            coef=A.coef*B.coef;
            S=S+coef*s; T=T+coef*t; Ven=Ven+coef*v;
        end
    end
end

function [S,T,Ven] = one_particle_primitive(alphaA,A,alphaB,B,Z,Rnuc)
    p=alphaA+alphaB; P=(alphaA*A+alphaB*B)./p; RAB2=sum((A-B).^2);
    NA=(alphaA/pi)^(3/4); NB=(alphaB/pi)^(3/4);
    K=NA*NB*exp(-(alphaA*alphaB/(2*p))*RAB2);
    S=K*(2*pi/p)^(3/2);
    T=0.5*alphaA*alphaB*(3/p-(alphaA*alphaB/p^2)*RAB2)*S;
    RP2=sum((P-Rnuc).^2);
    Ven=-Z*K*(4*pi/p)*boys0(0.5*p*RP2);
end

function val = eri_primitive_vec(alphaA,Ax,Ay,Az,alphaB,Bx,By,Bz,alphaC,Cx,Cy,Cz,alphaD,Dx,Dy,Dz)
    p=alphaA+alphaB; q=alphaC+alphaD;
    Px=(alphaA*Ax+alphaB.*Bx)./p; Py=(alphaA*Ay+alphaB.*By)./p; Pz=(alphaA*Az+alphaB.*Bz)./p;
    Qx=(alphaC*Cx+alphaD.*Dx)./q; Qy=(alphaC*Cy+alphaD.*Dy)./q; Qz=(alphaC*Cz+alphaD.*Dz)./q;
    RAB2=(Ax-Bx).^2+(Ay-By).^2+(Az-Bz).^2;
    RCD2=(Cx-Dx).^2+(Cy-Dy).^2+(Cz-Dz).^2;
    RPQ2=(Px-Qx).^2+(Py-Qy).^2+(Pz-Qz).^2;
    NA=(alphaA/pi)^(3/4); NB=(alphaB/pi).^(3/4); NC=(alphaC/pi)^(3/4); ND=(alphaD/pi).^(3/4);
    Kab=NA.*NB.*exp(-(alphaA.*alphaB./(2*p)).*RAB2);
    Kcd=NC.*ND.*exp(-(alphaC.*alphaD./(2*q)).*RCD2);
    arg=(p.*q./(2*(p+q))).*RPQ2;
    val=Kab.*Kcd.*(8*sqrt(2)*pi^(5/2))./(p.*q.*sqrt(p+q)).*boys0_vec(arg);
end

function F = boys0_vec(t)
    F=zeros(size(t)); small=t<1e-10;
    ts=t(small); F(small)=1-ts/3+ts.^2/10-ts.^3/42+ts.^4/216-ts.^5/1320;
    tl=t(~small); F(~small)=0.5*sqrt(pi)./sqrt(tl).*erf(sqrt(tl));
end

function F = boys0(t)
    if t<1e-10, F=1-t/3+t^2/10-t^3/42+t^4/216-t^5/1320; else, F=0.5*sqrt(pi)/sqrt(t)*erf(sqrt(t)); end
end

%% ========================================================================
% Local functions: solve, coarsen, diagnostics
% ========================================================================
function [E0,coeff,nkeep,info] = solve_ground_projected(H,S,mass_tol,verbose,targetEnergy,solverOpts)
    if nargin < 6 || isempty(solverOpts)
        solverOpts = struct();
    end
    if ~isfield(solverOpts,'projectBlockSize'), solverOpts.projectBlockSize = 256; end
    if ~isfield(solverOpts,'autoCapKeptDim'), solverOpts.autoCapKeptDim = false; end
    if ~isfield(solverOpts,'maxKeptDim'), solverOpts.maxKeptDim = inf; end

    M=size(S,1); t0=tic;

    % Matrices were already symmetrized after assembly.  Avoid another
    % sparse copy here unless explicitly requested.  Do NOT form full(H).
    if isfield(solverOpts,'forceSymmetrizeInSolver') && solverOpts.forceSymmetrizeInSolver
        S = (S+S')/2;
        H = (H+H')/2;
    end

    % Dense mass eigensolve is still the robust part of the old solver.
    % But we only densify S, not H. This removes one dense M-by-M matrix
    % from peak memory and avoids Hf/HX full copies.
    tMass = tic;
    Sf=full(S);
    [U,d]=eig(Sf,'vector');
    d=real(d(:));
    dmax=max(d);
    if ~isfinite(dmax) || dmax <= 0
        error('Invalid mass matrix in solve_ground_projected.');
    end

    localTol = mass_tol;
    keep=d > localTol*dmax;
    nkeep=nnz(keep);

    % Optional emergency cap.  Disabled by default because it changes the
    % effective variational space.  Enable only if the machine still OOMs.
    if solverOpts.autoCapKeptDim && nkeep > solverOpts.maxKeptDim
        [dsort,~] = sort(d,'descend');
        newTol = max(localTol, dsort(solverOpts.maxKeptDim)/dmax * (1+1e-12));
        keep = d > newTol*dmax;
        nkeep = nnz(keep);
        fprintf('    auto mass_tol cap: %.1e -> %.3e to keep %d directions.\n', localTol, newTol, nkeep);
        localTol = newTol;
    end

    if nkeep == 0
        error('No mass directions kept. mass_tol=%.3e', localTol);
    end

    X=U(:,keep);
    X = X .* (1./sqrt(d(keep))).';

    % Release dense S eigensystem before forming projected Hamiltonian.
    clear Sf U d keep;
    massTime = toc(tMass);

    % Horth = X' * H * X, computed blockwise through sparse H.
    % This gives the same projected dense Hamiltonian as the old solver,
    % but avoids full(H) and avoids storing H*X as a full M-by-nkeep matrix.
    tProj = tic;
    bs = solverOpts.projectBlockSize;
    Horth = zeros(nkeep,nkeep,'double');
    for j0 = 1:bs:nkeep
        j1 = min(nkeep, j0+bs-1);
        Xb = X(:,j0:j1);
        HXb = H * Xb;
        Horth(:,j0:j1) = X' * HXb;
        clear Xb HXb;
    end
    Horth=(Horth+Horth')/2;
    projTime = toc(tProj);

    tEig = tic;
    [V,Ediag]=eig(Horth,'vector');
    evals=real(Ediag(:));
    [~,idx]=min(evals);
    y=V(:,idx);
    clear V Ediag evals Horth;

    coeff=X*y;
    clear X y;
    coeff=coeff/sqrt(real(coeff'*S*coeff));

    % Compute final Rayleigh quotient and residual against the original sparse H,S.
    Hc = H*coeff; Sc = S*coeff;
    E0 = real(coeff' * Hc) / real(coeff' * Sc);
    res=norm(Hc-E0*Sc)/(max(1,norm(Hc))+max(1,abs(E0)*norm(Sc)));
    clear Hc Sc;

    info=struct('kept',nkeep,'residual',res,'time',toc(t0), ...
        'method','full-S-mass-projection+sparseH-block-projection', ...
        'massTime',massTime,'projectionTime',projTime,'eigTime',toc(tEig), ...
        'massTolUsed',localTol);
    if verbose
        fprintf('    mass eig M=%d kept=%d E=%.15f targetDiff=%.3e res=%.3e | mass %.1fs proj %.1fs eig %.1fs\n', ...
            M,nkeep,E0,E0-targetEnergy,res,massTime,projTime,info.eigTime);
    else
        fprintf('    solver=%s | kept=%d | mass %.1fs proj %.1fs eig %.1fs | massTol=%.1e\n', ...
            info.method,nkeep,massTime,projTime,info.eigTime,localTol);
    end
end

function [coarseBasis,S0,H0,E0,c0,records,idxBest,nuBest] = coarsen_basis_by_coeff(rawBasis,Sraw,Hraw,craw,Eraw,delta,mass_tol,verbose,Eref)
    coefAbs=abs(craw(:)); nuList=0:80;
    records=struct('nu',{},'thr',{},'M',{},'Mzero',{},'Mone',{},'Mtwo',{},'E',{},'dE',{},'idx',{});
    fprintf('\nCoarsening scan B(nu) = {|v_mu| >= 2^{-nu}}:\n');
    fprintf('   nu       threshold          M     Mzero   Mone   Mtwo_uu        E(nu)              dE\n');
    for inu=1:numel(nuList)
        nu=nuList(inu); thr=2^(-nu);
        idx=find(coefAbs>=thr); idx=unique([1;idx(:)],'stable');
        [Esub,~,~,~]=solve_ground_projected(Hraw(idx,idx),Sraw(idx,idx),mass_tol,verbose,Eref);
        dE=Esub-Eraw; counts=count_blocks(rawBasis(idx));
        records(inu).nu=nu; records(inu).thr=thr; records(inu).M=numel(idx); records(inu).Mzero=counts.zero;
        records(inu).Mone=counts.one_total; records(inu).Mtwo=counts.two_uu; records(inu).E=Esub; records(inu).dE=dE; records(inu).idx=idx;
        fprintf('%5d   %.6e   %6d   %5d  %5d  %7d   %.15f   %.3e\n',nu,thr,numel(idx),counts.zero,counts.one_total,counts.two_uu,Esub,dE);
    end
    valid=find([records.dE] <= delta+1e-12 & [records.dE] >= -1e-10);
    if isempty(valid)
        warning('No B(nu) satisfies dE <= delta; selecting largest candidate.'); [~,pos]=max([records.M]); selected=records(pos);
    else
        [~,loc]=min([records(valid).M]); selected=records(valid(loc));
    end
    idxBest=selected.idx; nuBest=selected.nu;
    coarseBasis=rawBasis(idxBest); S0=Sraw(idxBest,idxBest); H0=Hraw(idxBest,idxBest);
    [E0,c0,~,~]=solve_ground_projected(H0,S0,mass_tol,verbose,Eref);
end

function scores = partial_orthogonal_importance(c,S)
    c=c(:); M=numel(c);
    if M==1, scores=abs(c); return; end
    B11=full(S(1,1)); B12=full(S(1,2:end));
    z=c; z(1)=c(1)+(B12/B11)*c(2:end);
    diagPO=zeros(M,1); diagPO(1)=B11;
    diagPO(2:end)=full(diag(S(2:end,2:end))) - (B12(:).^2)/B11;
    diagPO=max(real(diagPO),0);
    scores=abs(sqrt(diagPO).*z);
end

function be = empty_block_energy()
    z=struct('zero',NaN,'one',NaN,'two_uu',NaN,'total',NaN);
    be=struct('row',z,'diag',z);
end

function be = compute_block_energy_contributions(c,H,twoBasis)
    be=empty_block_energy();
    blocks=strings(numel(twoBasis),1); for i=1:numel(twoBasis), blocks(i)=string(twoBasis(i).block); end
    idxZero=find(blocks=="zero"); idxOne=find(blocks=="one"); idxTwo=find(blocks=="two_uu");
    be.row.zero=row_energy(c,H,idxZero); be.row.one=row_energy(c,H,idxOne); be.row.two_uu=row_energy(c,H,idxTwo);
    be.row.total=be.row.zero+be.row.one+be.row.two_uu;
    be.diag.zero=diag_energy(c,H,idxZero); be.diag.one=diag_energy(c,H,idxOne); be.diag.two_uu=diag_energy(c,H,idxTwo);
    be.diag.total=be.diag.zero+be.diag.one+be.diag.two_uu;
end

function e=row_energy(c,H,idx)
    if isempty(idx), e=0; else, e=real(c(idx)'*(H(idx,:)*c)); end
end
function e=diag_energy(c,H,idx)
    if isempty(idx), e=0; else, e=real(c(idx)'*(H(idx,idx)*c(idx))); end
end

function gb=estimate_sparse_pair_gb(S,H)
    ns=nnz(S); nh=nnz(H); m=size(S,1); gb=(16*(ns+nh)+16*(m+1))/1024^3;
end
